apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  Messaging__RabbitMQ__Host: "rabbitmq-service"
  Messaging__RabbitMQ__Username: "guest"
  Messaging__RabbitMQ__Password: "guest"
  SWAGGER_BASE_PATH: "/notifications"
  NEW_RELIC_APP_NAME: "fcg-notifications-api"
